version: '3'
services:
  nginx:
    container_name: ng01
    build:
      context: nginx
    ports:
      - "80:80"
  web:
    build:
      context: prodjango
    container_name: dg01
    expose:
      - "8000"
  web1:
    build:
      context: prodjango2
    container_name: dg02
    expose:
      - "8000"
